spring:
  datasource:
    username: root
    password: root
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  h2:
    console:
       enabled: true
server:
  port: 9090
